# Generated by Django 3.1.7 on 2021-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('produto', models.CharField(max_length=40)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=5)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descrição', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
