# Generated by Django 3.1.7 on 2021-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre_Nos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=20)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sobre Nós',
            },
        ),
    ]
