# Generated by Django 3.1.7 on 2021-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_sobre_nos'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('nota', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Formulário',
            },
        ),
    ]
