# Generated by Django 3.1.7 on 2021-03-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
