# Generated by Django 3.1.7 on 2021-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_auto_20210309_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
