# Generated by Django 3.1.7 on 2021-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_auto_20210309_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nota',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
    ]
