# Generated by Django 3.1.7 on 2021-03-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_auto_20210309_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nota',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
